export const products = [
  {
    id: 1111,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "no",
    bigDiscount: "no",
    topRated: "no",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 290,
    rating: "4.2/5",
    shipping: "free",
    productName: "Sony V-4 Headphone",
    cetegory: "headphone",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 2222,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "highQuality",
    price: 400,
    rating: "4.4/5",
    shipping: "free",
    productName: "Apple smart watch",
    cetegory: "watch",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 3333,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "no",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "no",
    price: 280,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 4444,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "no",
    bigDiscount: "bigDiscount",
    topRated: "no",
    newProduct: "newProduct",
    highQuality: "no",
    price: 500,
    rating: "4.2/5",
    shipping: "paid",
    productName: "Televistion Sony V-4",
    cetegory: "television",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 5555,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "no",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "no",
    price: 325,
    rating: "4.4/5",
    shipping: "free",
    productName: "Xiaomi smart watch",
    cetegory: "watch",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 6666,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "no",
    newProduct: "no",
    highQuality: "highQuality",
    price: 1201,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Iphone 14 pro max",
    cetegory: "mobile",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },

  {
    id: 7777,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "no",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 1409,
    rating: "4.2/5",
    shipping: "free",
    productName: "Samsaung S20 Ultra",
    cetegory: "mobile",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 8888,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "no",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "no",
    price: 399,
    rating: "4.4/5",
    shipping: "paid",
    productName: "Apple smart watch v2",
    cetegory: "watch",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 9999,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "no",
    price: 599,
    rating: "4.9/5",
    shipping: "free",
    productName: "Apple smart glass v3.0",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 1010,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "no",
    price: 399,
    rating: "4.2/5",
    shipping: "free",
    productName: "Smart Television",
    cetegory: "television",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 1011,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "no",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "no",
    price: 390,
    rating: "4.4/5",
    shipping: "paid",
    productName: "Apple smart Television",
    cetegory: "television",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 1012,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "no",
    bigDiscount: "bigDiscount",
    topRated: "no",
    newProduct: "newProduct",
    highQuality: "no",
    price: 499,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass v4.0",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 234365456463,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "no",
    bigDiscount: "no",
    topRated: "no",
    newProduct: "no",
    highQuality: "no",
    price: 10,
    rating: "4.2/5",
    shipping: "free",
    productName: "Sony V-4 Headphone X copy",
    cetegory: "headphone",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 2342546644352,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "no",
    newProduct: "no",
    highQuality: "highQuality",
    price: 19,
    rating: "4.4/5",
    shipping: "free",
    productName: "Apple smart watch X plus",
    cetegory: "watch",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 53536777464353,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "no",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 300,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass x15",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 45634535667577534,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "no",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "no",
    price: 449,
    rating: "4.2/5",
    shipping: "paid",
    productName: "Sony V-4 Airbus",
    cetegory: "headphone",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 564756757646,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 50,
    rating: "4.4/5",
    shipping: "free",
    productName: "Apple TV controller",
    cetegory: "television",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 5647567576462423,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 31,
    rating: "4.4/5",
    shipping: "free",
    productName: "Apple TV controller copy",
    cetegory: "television",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 42424225453535353,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "no",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 70,
    rating: "4.9/5",
    shipping: "paid",
    productName: "RC plane",
    cetegory: "rctoy",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },

  {
    id: 423423423342422,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "highQuality",
    price: 20,
    rating: "4.2/5",
    shipping: "free",
    productName: "RC Racing Car",
    cetegory: "rctoy",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 2342423422424,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "no",
    price: "325$",
    rating: "4.4/5",
    shipping: "paid",
    productName: "Apple telephone v22",
    cetegory: "mobile",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 23423423423423424,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "no",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "highQuality",
    price: 325,
    rating: "4.9/5",
    shipping: "free",
    productName: "Apple Ipad mini",
    cetegory: "mobile",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 23424242342342342342,
    image: "./img/product1.jpg",
    inStock: 13,
    sold: "1.2k",
    mostSold: "mostSold",
    bigDiscount: "no",
    topRated: "topRated",
    newProduct: "no",
    highQuality: "highQuality",
    price: 290,
    rating: "4.2/5",
    shipping: "free",
    productName: "Sony V-4 Headphone",
    cetegory: "headphone",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 234242442424242,
    image: "./img/product5.jpg",
    inStock: 15,
    sold: "11k",
    mostSold: "no",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "no",
    price: 600,
    rating: "4.4/5",
    shipping: "paid",
    productName: "Apple Ipad air",
    cetegory: "mobile",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 422242424242,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 400,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 367463746374673,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 600,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass XXX",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 87638726487264782,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 1000,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass xxxv4",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
  {
    id: 767824287643,
    image: "./img/product3.jpg",
    inStock: 10,
    sold: "12k",
    mostSold: "mostSold",
    bigDiscount: "bigDiscount",
    topRated: "topRated",
    newProduct: "newProduct",
    highQuality: "highQuality",
    price: 59,
    rating: "4.9/5",
    shipping: "paid",
    productName: "Apple smart glass master copy",
    cetegory: "glass",
    productDescription:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro impedit, nihil quia placeat autem commodi.",
  },
];
